FROM wasys/wildfly
LABEL authors="Bruno Scrok Brunoro"
LABEL email="bruno.brunoro@wasys.com.br"

USER root

COPY ./standalone.xml /opt/jboss/wildfly/standalone/configuration

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]