package net.wasys.getdoc.domain.enumeration;

public enum AcaoDocumento {

	CRIACAO_INCLUIDO,
	CRIACAO_EXCLUIDO,
	DIGITALIZOU,
	MOVEU_IMAGEM,
	COPIOU_IMAGEM,
	EXCLUIU_IMAGEM,
	APROVOU,
	APROVOU_PARCIALMENTE,
	REJEITOU,
	JUSTIFICOU,
	INCLUSAO,
	EXCLUSAO,
	TIPIFICOU,
	ALTERACAO_OBRIGATORIEDADE,
	ALTERACAO_STATUS,
	RECORTE_IMAGEM,
	NOTIFICACAO_SIA_ERRO,
	NOTIFICACAO_SIA,
	REAPROVEITADO,
}
