package net.wasys.getdoc.domain.enumeration;

public enum SubRegraAcoes {
	ALTERAR_STATUS_DOCUMENTO,
	ALTERAR_OBRIGATORIEDADE_DOCUMENTO,
	ADICIONAR_GRUPO_NO_PROCESSO,
	ALTERAR_VALOR_CAMPO,
	ALTERAR_OBRIGATORIEDADE_CAMPO
}
