/**
 * AtendeCliente.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package net.wasys.util.correiows;

public interface AtendeCliente extends java.rmi.Remote {
    public java.lang.Long fechaPlp(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.lang.String faixaEtiquetas, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.Retorno[] registrarPedidosInformacao(net.wasys.util.correiows.PedidoInformacaoRegistro[] pedidosInformacao, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.ClienteERP buscaCliente(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public boolean validaEtiquetaPLP(java.lang.String numeroEtiqueta, java.lang.Long idPlp, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public boolean verificaDisponibilidadeServico(java.lang.Integer codAdministrativo, java.lang.String numeroServico, java.lang.String cepOrigem, java.lang.String cepDestino, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.StatusPlp getStatusPLP(net.wasys.util.correiows.ObjetoPostal[] arg0, java.lang.String arg1) throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String bloquearObjeto(java.lang.String numeroEtiqueta, java.lang.Long idPlp, net.wasys.util.correiows.TipoBloqueio tipoBloqueio, net.wasys.util.correiows.Acao acao, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String solicitaEtiquetas(java.lang.String tipoDestinatario, java.lang.String identificador, java.lang.Long idServico, java.lang.Integer qtdEtiquetas, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.MensagemRetornoPIMaster[] obterMensagemRetornoPI() throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.Retorno[] consultarPedidosInformacao(net.wasys.util.correiows.PedidoInformacaoConsulta[] pedidosInformacao, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String buscaPagamentoEntrega(java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public int[] geraDigitoVerificadorEtiquetas(java.lang.String[] etiquetas, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.Boolean validarPostagemReversa(java.lang.Integer codAdministrativo, java.lang.Integer codigoServico, java.lang.String cepDestinatario, net.wasys.util.correiows.ColetaReversaTO coleta, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.Long fechaPlpVariosServicos(java.lang.String xml, java.lang.Long idPlpCliente, java.lang.String cartaoPostagem, java.lang.String[] listaEtiquetas, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.Boolean cancelarObjeto(java.lang.Long idPlp, java.lang.String numeroEtiqueta, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException, net.wasys.util.correiows.Exception;
    public boolean validaPlp(long cliente, java.lang.String numero, long diretoria, java.lang.String cartao, java.lang.String unidadePostagem, java.lang.Long servico, java.lang.String[] servicosAdicionais, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.Boolean validarPostagemSimultanea(java.lang.Integer codAdministrativo, java.lang.Integer codigoServico, java.lang.String cepDestinatario, net.wasys.util.correiows.ColetaSimultaneaTO coleta, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.EmbalagemLRSMaster[] obterEmbalagemLRS() throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.RetornoCancelamentoTO cancelarPedidoScol(java.lang.Integer codAdministrativo, java.lang.String idPostagem, java.lang.String tipo, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.ServicoERP[] buscaServicos(java.lang.String idContrato, java.lang.String idCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String solicitarPostagemScol(java.lang.Integer codAdministrativo, java.lang.String xml, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String solicitaPLP(java.lang.Long idPlpMaster, java.lang.String numEtiqueta, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.StatusCartao getStatusCartaoPostagem(java.lang.String numeroCartaoPostagem, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String solicitaXmlPlp(java.lang.Long idPlpMaster, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.MotivoPIMaster[] obterMotivosPI() throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.ContratoERP buscaContrato(java.lang.String numero, long diretoria, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.String consultaSRO(java.lang.String[] listaObjetos, java.lang.String tipoConsulta, java.lang.String tipoResultado, java.lang.String usuarioSro, java.lang.String senhaSro) throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public java.util.Calendar obterClienteAtualizacao(java.lang.String cnpjCliente, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public java.lang.Boolean integrarUsuarioScol(java.lang.Integer codAdministrativo, java.lang.String usuario, java.lang.String senha) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public boolean atualizaPLP(java.lang.Long idPlpMaster, java.lang.String numEtiqueta, java.lang.String usuario, java.lang.String senha, java.lang.String xml) throws java.rmi.RemoteException, net.wasys.util.correiows.AutenticacaoException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.AssuntoPIMaster[] obterAssuntosPI() throws java.rmi.RemoteException, net.wasys.util.correiows.SigepClienteException;
    public net.wasys.util.correiows.EnderecoERP consultaCEP(java.lang.String cep) throws java.rmi.RemoteException, net.wasys.util.correiows.SQLException, net.wasys.util.correiows.SigepClienteException;
}
